spring:
  profiles:
    default: dev

  mvc:
    hidden-method:
      filter:
        enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/in__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ENC(HIzHQ75JvxOgtkxajoqlEA==)
    password: ENC(37glGXQV2EiQ926e1Na6TVNN64bRwxlT)

  security:
    oauth2:
      client:
        registration:
          kakao:
            scope: profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
            clientId: ENC(b+fkQMzqlkGg8s2x3Zu+nHuISd2tlVBjzfuWYde22fUiUnfTXf2C2w5togefVw0k)
          google:
            scope: profile
            client-name: Google
            redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
            clientId: ENC(qbe5qvL4sOPf/Wugu4mMTtM4XY5O8Wp0B+S5FE2IbqPpRbxgkMSa9eb0b/NsbNY3NxFa93JOvOQReSZKxlMRHunjEhaDw8dY/FQVr8HE8YEeqvJxbe/NNA==)
            client-secret: ENC(syyok3nI4CUx8QcxwHjUpzP7yhakU0wrYmMDvMQV/eiUE7iY6AvMr7PnUNP12Ksr)
          github:
            clientId: ENC(NYNzs6okzII64/4rbBQ6NN0nDj4Zc+SofwLeX/dMndA=)
            client-secret: ENC(tzLcF+J3nBHmE5wBUsR0lqHdrZ1ntjZfC5Mm7yzTKcV4LpAD5dKpwSxmVBurSpsMpag6T/I/p0Q=)
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging.level:
  org.hibernate:
    SQL: debug
    orm.jdbc.bind: trace

custom:
  member:
    rating:
      senior:
        min: 10

  firebase:
    project_id: ENC(4y9KglFuYXIgVfkcJ8UvuQeUYTkKmTZK)
    private_key_id: ENC(+J/FycQ6bs8khHdhU3K9UnZ86l3wKOn9wtBJqOQdPO0LOXul9WS0gRakyhGl5TThlYcAsWfUxaE=)
    private_key: ENC(Whap2d8h+/mtt3Xo6cxn7HmxtCzIeTTFyv6RXn3MqcmKz7V7i4cYcXC07vg/rnqep40kisfYcxF8m06O2bDz0BAS/UjXMvgGHL1LcmhZ+hqwHGPbn/CUbD8qh5AesV9wap2EcbQoC8g542YGonRM1lWvzttpsCcyL6IX166xGJahsRuBwY3yxXVq7u4Fk9NO2TWyPc1vKNZcBaEtXJbdyOPdJFgMBnEe6HyuBjegF0ZX3Ot3dzlDLcBEVWvUkWUwij3F+bAcnIZ/1pRlvKlfl+fall2I9y5FOEybCy6B2jYQLF9TooDlACRXi+App3JatyZu9tt/AaQPLkq3Wl5FRv7IlI3lO1nrR0AJVLo+BWDm0k5jKlw6Qp374WEr/RkaLQDs8VSzUHMfJX8m4t7+wek/BqnL8BNrTrFV29GywCDjv6XfRESORaXwffvucttg3WrNpH47cyevVKZJeGCQasCJqgnDvYTAJRXo8BPnP6NFjMS16S3OcQwN4ZOIHzB5/A05xVzYKbkKtmraXvlkCU3pKxNDhXyGQNRyMetD+jQHFNCNBQFKSwivEC6xd3BZEzLaKoWVPAvzqYtYEHF/k+x/QOIet8zhMTlWrNJWSmZ8a/jy4oj/SoGln1V75ONCnoJROWK0H1BgsaerOFkYd6zvxxoZYqAyvTLj/3ImFWz/FISPiGmjcnSlkfUBH6WdalbhfXPC2cZwOxeevLCjKvr4ci8GdNwRmIemuP5VLvoHnpjmWqrphlKSf/RVjQ6YAb1AOvjEIa4JuvP6thz1Z7aoW3aqG7tn/FSHH4j/vvNN9KVltpd/+ia2QzfOlueQOuc00LslvkU3IitNRjvbLhq0CwY88OB0CWRORvF9kJR5a5U15vLXF4JUx+yz+EibONJa6iSiXgq0zLglff9iZM0iEwJlWFDbPAywUKpU5W0nwpB1632XwBQeg9fG5NfGSB2rnma017UDGb6KcArGnL485TCpvG3fhjC6fLjqkZsLmZiGoO8RyL+uEdqSSTsY4XeAAXZJPhdNm5999MhcsvvY12VvaxJlfF2aqJb3VJhMUsKTaMouoE4qbADdDKNxR0uaNzkVQgkskR8aS9JKepP8g2M8saC2BlJSEboA444EloMnrcS2Q3dW8lLwEj19t3GlVDqO6xxwklpA9/CK3Afk85GATiR0vTjrhrYgw8JYxYCA7KgR+iww36q5DMIWI0OeNa8IUh71SQ3p4mlce3GfEuqBVRzUdr4L5U9Bn1jZHpm6MFJrC3iH8bsYUNTC4W1jXZZVFoP/9i8Xl06GZiIwIFEJS9YUG5SCsGQU1I0dKKVQU8PzwQQv+ZWpNsvDhUWlT0HVX8Kt3ls5786w/TcFDv8RZVxivvLqXfAfYpvJ6AmBHJUJnrOTwjR5fsLCkHVGJYwoXsxPrHb8y2Su3VkiKYCFu1foC0mQ1mUevckew7VXQ2XuinN+b6OC1NjY5EL056h7h5767C0HMx2oNqlmz9QpYziZEpnig1e6RFeBIKJpoutnkdo9BZGq92uEb2whMZ5c0x5a8KZsOWGGMuKCQZ5PJL/XwW5WQqoE1LoOXgmidwahE5AN4LRUazdat19nU3r72VLFvQTumUwg1c2eIE+35JbmUEmXKPenO3bXaGskQbrVuC57TKGp+3uP3XLoFMNkTJUn9CIJalr00/eFAHyG9kBlNrtpwHFItqo8PvuKWkJ5qI8MVp5+jWOh8quw0BUjGIjxoWmIYXdnBejfW/C0aJUN6d2fshoQptSWUqkUFfVIwh6OF6SH6esZ2mr4Gd/O1tcsdqufJMsF8v8uwC0FHHOQHd8gT3fQ6pJeNhWd4lZCK8stqrVItODXe99L2ilsE3zVqcNj9YQJw21mKYqW+qtX9sn8qgik6S8dn3TsyKrRSWZre/nrfPIbKS9IQLxOWt/m7U3eOfXqErkwVEMuLb36sXDhYN5e66zZsCUUfLZJ2vdbW4tr1JrNZ/wyv2Iid//fbKmDQ2TosZmQT0NRThgqWxkBiy8en2gKd+I7jKc/yItfVj4nOhR0wr3mSpafTKcESYM0ylDBO7h9JU4JcyJWX4Zcb7kx9iBbDzZ3/6mNWX57+r0fft/WksBiOwS9b1Wfv4EvlsPzIhrFf7v96z646gE8/0pePDMDckeYpjtwBmHMWiAeIUd82moIy+uNYYqEv8RK8A2cHQWx7UsPyf9YvQ0pOudD6vCkaZQfzONiwGhMbqal1OsB1yO2EtjlZtZK7iTS96OTvUBTYCbclYC1n+Q+GTP9V+KskYAYjhe7lIAhZMU8hh9E7nm8HQvuUfJpKXhz19kWtg==)
    client_email: ENC(V8CmhVYjlxOsYuBSXUxj60NaG+Glho+gwpyQUxr7DMtTKSrFcSH2wWfsPm/Fm4p4nc/5HqF6QbkjIQCrqJsVv8brgEvfYyGP)
    client_id: ENC(KtbbQ94jgVaZiCeh5k03dB3Qh2h+26RPd5vhXKbSLTU=)


  site:
    baseUrl: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

cloud:
  aws:
    credentials:
      access-key: ENC(pEYlwtCwB2ZSJsSq3FZx31Z/dw52pOVLAgfta14zqAc=)
      secret-key: ENC(qOkY2GwBawtcQJ1hxO9zI53PZBUVWTY6i5t10uHqaNFQDf5SOk4709oqX6MlXgiCrJ2xkn468sk=)
    s3:
      bucket: inhub-image
      storage: local
    region:
      static: ap-northeast-2
    stack:
      auto: false

chatGpt:
  api-key: ENC(9CDdUyEmkDiEAAuT5CdKL0CH37yvdO3JzvIrGPG5s2uT7VRW0uLuzROrRiWDcRXReoyTP9bYTYAG0eGUhpQsjw==)


mail:
  naver:
    host: smtp.naver.com
    port: 465
    id: ENC(uBlznD8q13Gu5H2ZSsuTGj1KvQje1zDJ)
    pw: ENC(3u4EC7y3xwYqN5Fqryj+YX9OLEYWE5kS)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
