spring:
  profiles:
    default: dev

  mvc:
    hidden-method:
      filter:
        enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/in__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ENC(HIzHQ75JvxOgtkxajoqlEA==)
    password: ENC(37glGXQV2EiQ926e1Na6TVNN64bRwxlT)

  security:
    oauth2:
      client:
        registration:
          kakao:
            scope: profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
            clientId: ENC(b+fkQMzqlkGg8s2x3Zu+nHuISd2tlVBjzfuWYde22fUiUnfTXf2C2w5togefVw0k)
          google:
            scope: profile
            client-name: Google
            redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
            clientId: ENC(qbe5qvL4sOPf/Wugu4mMTtM4XY5O8Wp0B+S5FE2IbqPpRbxgkMSa9eb0b/NsbNY3NxFa93JOvOQReSZKxlMRHunjEhaDw8dY/FQVr8HE8YEeqvJxbe/NNA==)
            client-secret: ENC(syyok3nI4CUx8QcxwHjUpzP7yhakU0wrYmMDvMQV/eiUE7iY6AvMr7PnUNP12Ksr)
          github:
            clientId: ENC(NYNzs6okzII64/4rbBQ6NN0nDj4Zc+SofwLeX/dMndA=)
            client-secret: ENC(tzLcF+J3nBHmE5wBUsR0lqHdrZ1ntjZfC5Mm7yzTKcV4LpAD5dKpwSxmVBurSpsMpag6T/I/p0Q=)
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging.level:
  org.hibernate:
    SQL: debug
    orm.jdbc.bind: trace

custom:
  member:
    rating:
      senior:
        min: 10

  firebase:
    type: service_account
    project_id: ENC(4y9KglFuYXIgVfkcJ8UvuQeUYTkKmTZK)
    private_key_id: ENC(+J/FycQ6bs8khHdhU3K9UnZ86l3wKOn9wtBJqOQdPO0LOXul9WS0gRakyhGl5TThlYcAsWfUxaE=)
    client_email: ENC(V8CmhVYjlxOsYuBSXUxj60NaG+Glho+gwpyQUxr7DMtTKSrFcSH2wWfsPm/Fm4p4nc/5HqF6QbkjIQCrqJsVv8brgEvfYyGP)
    client_id: ENC(KtbbQ94jgVaZiCeh5k03dB3Qh2h+26RPd5vhXKbSLTU=)
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://oauth2.googleapis.com/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-cgp8c%40inhub-50c3d.iam.gserviceaccount.com
    universe_domain: googleapis.com


  site:
    baseUrl: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

cloud:
  aws:
    credentials:
      access-key: ENC(pEYlwtCwB2ZSJsSq3FZx31Z/dw52pOVLAgfta14zqAc=)
      secret-key: ENC(qOkY2GwBawtcQJ1hxO9zI53PZBUVWTY6i5t10uHqaNFQDf5SOk4709oqX6MlXgiCrJ2xkn468sk=)
    s3:
      bucket: inhub-image
      storage: local
    region:
      static: ap-northeast-2
    stack:
      auto: false

chatGpt:
  api-key: ENC(9CDdUyEmkDiEAAuT5CdKL0CH37yvdO3JzvIrGPG5s2uT7VRW0uLuzROrRiWDcRXReoyTP9bYTYAG0eGUhpQsjw==)


mail:
  naver:
    host: smtp.naver.com
    port: 465
    id: ENC(uBlznD8q13Gu5H2ZSsuTGj1KvQje1zDJ)
    pw: ENC(3u4EC7y3xwYqN5Fqryj+YX9OLEYWE5kS)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
